/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Jovi Julian
 */
import java.sql.*;
import javax.swing.table.DefaultTableModel;
public class FormNilai extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormNilai
     */
    Connection con;
    DefaultTableModel tm;
    public FormNilai() {
        initComponents();
        connect();
        refreshTable();
        TampilIdMapel();
        TampilNis();
        TampilKodeJurusan();
        TampilKodeKelas();
        
    }
    private void TampilIdMapel(){
        String sql = "Select * from mapel";
    try{
    PreparedStatement ps = con.prepareStatement(sql);
    ResultSet rs = ps.executeQuery();
    while(rs.next()){
        idmapel.addItem(rs.getString("idmapel"));
            }
            }catch(Exception e){
        }
    }
    
    private void TampilNis(){
        String sql = "Select * from murid";
    try{
    PreparedStatement ps = con.prepareStatement(sql);
    ResultSet rs = ps.executeQuery();
    while(rs.next()){
        nis.addItem(rs.getString("nis"));
            }
            }catch(Exception e){
        }
    }
    
    private void TampilKodeJurusan(){
        String sql = "Select * from jurusan";
    try{
    PreparedStatement ps = con.prepareStatement(sql);
    ResultSet rs = ps.executeQuery();
    while(rs.next()){
        kodejurusan.addItem(rs.getString("kodejurusan"));
            }
            }catch(Exception e){
        }
    }
    
    private void TampilKodeKelas(){
        String sql = "Select * from kelas";
    try{
    PreparedStatement ps = con.prepareStatement(sql);
    ResultSet rs = ps.executeQuery();
    while(rs.next()){
        kodekelas.addItem(rs.getString("kodekelas"));
            }
            }catch(Exception e){
        }
    }
    
    private void connect() {
        con = null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/dbtugas", "root", "");
        } catch(Exception e){
            System.out.println("Error koneksi ke database\n" + e);
        }
    }

    private void refreshTable(){
        tm = new DefaultTableModel(
        null, new Object[]{"Kode Nilai","ID Mapel","NIS" , "Kode Jurusan", "Kode Kelas","Nilai"}
        );
        tbnilai.setModel(tm);
        tm.getDataVector().removeAllElements();
        
        try{
            PreparedStatement s = con.prepareStatement("SELECT * FROM nilai");
            ResultSet r = s.executeQuery();
            while(r.next()){
                Object[] data = {
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6)
                };
                tm.addRow(data);
            }
        } catch (Exception e){
            System.out.print("Error Query ke Database: \n" + e + "\n\n");
        }           
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbnilai = new javax.swing.JTable();
        nis = new javax.swing.JComboBox<>();
        kodejurusan = new javax.swing.JComboBox<>();
        kodekelas = new javax.swing.JComboBox<>();
        nuh = new javax.swing.JTextField();
        idmapel = new javax.swing.JComboBox<>();
        nuts = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nuas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        kodenilai = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel3.setText("NIS");

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Kode Jurusan");

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Kode Kelas");

        jLabel6.setText("Nilai UH");

        jLabel7.setText("Nilai UTS");

        jLabel8.setText("Nilai UAS");

        tbnilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbnilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbnilaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbnilai);

        nis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih NIS" }));

        kodejurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kode Jurusan" }));

        kodekelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kode Kelas" }));

        nuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuhActionPerformed(evt);
            }
        });

        idmapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih ID Mapel" }));
        idmapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmapelActionPerformed(evt);
            }
        });

        nuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Data Nilai");

        nuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuasActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Mapel");

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Kode Nilai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton2))
                                    .addComponent(jLabel8))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nuas)
                                    .addComponent(jButton3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(158, 158, 158)
                                .addComponent(nuts))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(nuh))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(kodekelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kodejurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel1)
                                                    .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(idmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kodenilai, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(kodenilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(idmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel3))
                                    .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel4))
                            .addComponent(kodejurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5))
                    .addComponent(kodekelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuhActionPerformed

    private void idmapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmapelActionPerformed

    }//GEN-LAST:event_idmapelActionPerformed

    private void nutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutsActionPerformed

    private void nuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    double nilaiuh,nilaiuts, nilaiuas, totalnilai;
    String nilaisiswa;
     nilaiuh = Double.parseDouble(nuh.getText());
     nilaiuts = Double.parseDouble(nuts.getText());
     nilaiuas = Double.parseDouble(nuas.getText());
    
    totalnilai = (nilaiuh+nilaiuts+nilaiuas)/3;
    nilaisiswa = String.valueOf(totalnilai);
        try{
           PreparedStatement ps = con.prepareStatement("INSERT INTO nilai VALUES (?,?,?,?,?,?)");
           ps.setString(1, kodenilai.getText());
           ps.setString(2, (String) idmapel.getSelectedItem());
           ps.setString(3, (String) nis.getSelectedItem());
           ps.setString(4, (String) kodejurusan.getSelectedItem());
           ps.setString(5, (String) kodekelas.getSelectedItem());
           ps.setString(6, nilaisiswa);
//           ps.setString(7, (String) nis.getSelectedItem());
           
           ps.executeUpdate();
           ps.close();
           refreshTable();
           kodenilai.setText("");
           idmapel.setSelectedItem("");
           nis.setSelectedItem("");
           kodejurusan.setSelectedItem("");
           kodekelas.setSelectedItem("");
           nuh.setText("");
           nuts.setText("");
           nuas.setText("");
           
       }catch (Exception e){
           System.out.print("Error Query ke database:\n" + e + "\n\n");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       double nilaiuh,nilaiuts, nilaiuas, totalnilai;
     String nilaisiswa;
     nilaiuh = Double.parseDouble(nuh.getText());
     nilaiuts = Double.parseDouble(nuts.getText());
     nilaiuas = Double.parseDouble(nuas.getText());
    
    totalnilai = (nilaiuh+nilaiuts+nilaiuas)/3;
    nilaisiswa = String.valueOf(totalnilai);
        try{
           PreparedStatement ps = con.prepareStatement("UPDATE nilai SET idmapel=?, nis=?, kodejurusan=?, kodekelas=?, nilaisiswa=? where kodenilai=?");
           ps.setString(1,(String) idmapel.getSelectedItem());
           ps.setString(2,(String) nis.getSelectedItem());
           ps.setString(3,(String) kodejurusan.getSelectedItem());
           ps.setString(4,(String) kodekelas.getSelectedItem());
           ps.setString(5, nilaisiswa);
           ps.executeUpdate();
           
           refreshTable();
           idmapel.setSelectedItem("");
           nis.setSelectedItem("");
           kodejurusan.setSelectedItem("");
           kodekelas.setSelectedItem("");
           nuh.setText("");
           nuts.setText("");
           nuas.setText("");
       }catch (Exception e){
           System.out.print("Error Query ke Database:\n" + e + "\n\n");
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
           PreparedStatement ps = con.prepareStatement("DELETE FROM nilai WHERE kodenilai=?");
           ps.executeUpdate();
           
           refreshTable();
           idmapel.setSelectedItem("");
           nis.setSelectedItem("");
           kodejurusan.setSelectedItem("");
           kodekelas.setSelectedItem("");
           nuh.setText("");
           nuts.setText("");
           nuas.setText("");
       }catch (Exception e){
           System.out.print("Error Query ke Database:\n" + e + "\n\n");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbnilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbnilaiMouseClicked
        idmapel.setSelectedItem(tm.getValueAt(tbnilai.getSelectedRow(),1). toString());
        nis.setSelectedItem(tm.getValueAt(tbnilai.getSelectedRow(),2). toString());
        kodejurusan.setSelectedItem(tm.getValueAt(tbnilai.getSelectedRow(),3). toString());
        kodekelas.setSelectedItem(tm.getValueAt(tbnilai.getSelectedRow(),4). toString());
       
    }//GEN-LAST:event_tbnilaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> idmapel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kodejurusan;
    private javax.swing.JComboBox<String> kodekelas;
    private javax.swing.JTextField kodenilai;
    private javax.swing.JComboBox<String> nis;
    private javax.swing.JTextField nuas;
    private javax.swing.JTextField nuh;
    private javax.swing.JTextField nuts;
    private javax.swing.JTable tbnilai;
    // End of variables declaration//GEN-END:variables
}
